#!/usr/bin/env bash
#
# setup global git settings after install
source script/helpers

set -e

# Add after install message to set git author config
cat > "$AFTERINSTALL" <<EOF
  * Be sure your git author config is correct in ~/.gitconfig.local:

      [core]
        name = YOUR_NAME
        email = YOUR_EMAIL
EOF

# Clone the newest hub
git clone https://github.com/github/hub.git

# In hub directory
pushq ./hub

  # build hub binary
  ./script/build

  # move built binary to $DOTFILES/bin/hub
  yes | cp -rf ./bin/hub $DOTFILES/bin/hub
  chmod +x $DOTFILES/bin/hub

# reset dir
popq

rm -rf ./hub

