#!/usr/bin/env bash
#
# setup global git settings after install
source script/helpers

inf 'setup git'
# TODO: install hub here
# process is:
#   1. clone the repo
#
#      `git clone https://github.com/github/hub.git`
#
#   2. in new repo directory run
#
#      `./script/build`
#
#   3. move the new binary to a PATH location
#
#      `mv ./bin/hub ~/.bin`
#
#   4. delete the cloned folder hub.git
#
# The process is the same for updating, we'll just force the
# move to overwrite previously built hub binary

# Add after install message to set git author config
cat > $AFTERINSTALL << EOF
From Git

  Be sure to setup your git author config in ~/.gitconfig.local:

    [core]
      name = YOUR_NAME
      email = YOUR_EMAIL

End Git
EOF

