#!/usr/bin/env bash
#
# Installs the heroku toolbelt
# Add after install message to login
source script/helpers

set -e

amessage Heroku "
  * start using the heroku-toolbelt by logging in with:

      \`heroku login\`
"
