#!/usr/bin/env bash
#
# setup vim after install
source script/helpers

export VIM_DIR="$HOME/.vim"
export JANUS_DIR="$VIM_DIR/janus"

function janus_dirs {
  ensure_dir "$VIM_DIR/_backup"
  ensure_dir "$VIM_DIR/_temp"
}

function janus_update {
  pushq "$VIM_DIR"
    eval "
      git clean -xdf -- "$JANUS_DIR" ${SILENCE_ALL}
      git pull ${SILENCE_ALL}
      git submodule sync ${SILENCE_ALL}
      git submodule update --init ${SILENCE_ALL}
    "
  popq
}

if [ -z ${DOTUPDATE+x} ];then
  rm -rf "$VIM_DIR"
  eval git clone --recursive https://github.com/carlhuda/janus.git $VIM_DIR/ $SILENCE_ALL

  janus_dirs
fi

janus_update

