#!/bin/bash

inf () {
  printf "\r\n  [ \033[00;34m..\033[0m ] $1\n"
}

user () {
  printf "\r\n  [ \033[0;33m??\033[0m ] $1\n"
}

success () {
  printf "\r\n\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\n\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
}

die () {
  fail "${@}"
  exit 1
}

sudo-heartbeat () {
  # fork sudo heartbeat to prevent sudo timeout while installing
  while true; do sleep 60; sudo -n true; kill -0 "$$" || exit; done 2>/dev/null &
}

ensure-sudo () {
  if [[ $UID != 0 ]]; then
    die "Dot.minatrix requires sudo to install"
  fi
  sudo-heartbeat
}
