#!/bin/bash
#
# A collection of bash functions for fun and profit
source $DOTFILES/bash/colors.bash

if [ "$VERBOSE" = '' ];then
  # silence inner commands when not verbose
  export SILENCE_STD="> /dev/null"
  export SILENCE_ALL="$SILENCE_STD 2>&1"
else
  # deactivate silence when verbose is set
  export SILENCE_STD=''
  export SILENCE_ALL=''
fi

inf () {
	if ! [ "$QUIET" = "1" ];then
    printf "\r\n\033[2K  [$Blue .. $Color_Off] $1\n"
	fi
}

user () {
  printf "\r\n\033[2K  [$Yellow ?? $Color_Off] $1\n"
}

success () {
	if ! [ "$QUIET" = "1" ];then
    printf "\r\n\033[2K  [$Green OK $Color_Off] $1\n"
  fi
}

tada () {
  printf "\r\n\n\033[2K  [$IGreen \(^-^)/ $Color_Off] $1\n\n"
}

fuck () {
  printf "\r\n\n\033[2K  [$IRed /{>_<}\ $Color_Off] $1\n\n"
}

failure () {
  printf "\r\n\033[2K  [$Red FAIL $Color_Off] $1\n"
}

die () {
  fuck "${@}"
  exit 1
}

sudo-heartbeat () {
  # fork sudo heartbeat to prevent sudo timeout while installing
  while true; do sleep 60; sudo -n true; kill -0 "$$" || exit; done 2>/dev/null &
}

ensure-sudo () {
  if [[ $UID != 0 ]]; then
    die "Dot.minatrix requires sudo to install"
  fi
  sudo-heartbeat
}

pushq () {
  pushd $1 >/dev/null
}

popq () {
  popd $1 >/dev/null
}

function ensure_dir {
  if ! [ -d "$1" ];then
    mkdir -p "$1"
  fi
}

function colors {
  for i in {0,3,4,9,10};do
    for j in {0..9};do
      C="\x1b[${i}${j}m";
      echo -en "$C";
      echo -n  "$C";
      [ $i -eq 10 ] && echo -en "\x1b[0m ";
      [ $i -ne 10 ] && echo -en "\x1b[0m  ";
    done
    echo
  done
  for i in {0..255};do
    [ $((i % 10)) -eq 0 ] && echo
    C="\x1b[38;5;${i}m";
    echo -en "$C";
    echo -n  "$C";
    [ $i -lt 10 ] && echo -en "\x1b[0m   " && continue
    [ $i -lt 100 ] && echo -en "\x1b[0m  " && continue
    echo -en "\x1b[0m "
  done
  echo
}

function amessage {
  title="
 _______
/
|  $1
|"

  if [ "$AFTERINSTALL" = '' ];then
    # no running collection file, just echo
    echo "$title"
    echo "$2"
  else
    echo "$title" >> "$AFTERINSTALL"
    echo "$2" >> "$AFTERINSTALL"
  fi
}
