#!/bin/bash

inf () {
  printf "\r\n  [$Blue .. $Color_Off] $1\n"
}

user () {
  printf "\r\n  [$Yellow ?? $Color_Off] $1\n"
}

success () {
  printf "\r\n\033[2K  [$Green OK $Color_Off] $1\n"
}

tada () {
  printf "\r\n\n\033[2K  [$IGreen \(^-^)/ $Color_Off] $1\n\n"
}

fuck () {
  printf "\r\n\n\033[2K  [$IRed /{>_<}\ $Color_Off] $1\n\n"
}

fail () {
  printf "\r\n\033[2K  [$Red FAIL $Color_Off] $1\n"
}

die () {
  fuck "${@}"
  exit 1
}

sudo-heartbeat () {
  # fork sudo heartbeat to prevent sudo timeout while installing
  while true; do sleep 60; sudo -n true; kill -0 "$$" || exit; done 2>/dev/null &
}

ensure-sudo () {
  if [[ $UID != 0 ]]; then
    die "Dot.minatrix requires sudo to install"
  fi
  sudo-heartbeat
}

pushq () {
  pushd $1 >/dev/null
}

popq () {
  popd $1 >/dev/null
}
