#!/bin/bash
#
# Run package installation and all topic installers.

set -e

if [ -z ${DOTFILES+x} ];then
  export DOTFILES=~/dot.minatrix
fi

source $DOTFILES/script/helpers

ensure-sudo

cd "$(dirname $0)"/..

shopt -s extglob

# load default packages
source packages.bash

# Don't install ppas when updating
if [ -z ${DOTUPDATE+x} ];then
  for ppa in "${ppalist[@]}"; do
    inf "Adding custom PPA: ppa:$ppa"
    add-apt-repository "ppa:$ppa" -y
    success "Added ppa:$ppa"
  done
fi

inf 'updating package info'
apt update
success 'packages updated'

inf 'Installing core packages'
apt install ${packagelist[@]}
success 'installed core packages'

# find the installers and run them iteratively
export AFTERINSTALL='./AFTER_INSTALL_MESSAGE'

for file in ./!(script)/install; do
  if [ -f "$file" ] && [ -x "$file" ];then
    inf "installing $file"
    $file

    if [ $? = 0 ];then
      success "installed $file"
    else
      fail "Error installing $file"
    fi
  fi
done

# Don't bootstrap when updating
if [ -z ${DOTUPDATE+x} ];then
  inf 'bootstrapping dot files'
  $DOTFILES/script/bootstrap

  if [ $? = 0 ];then
    success 'bootstrap complete'
  else
    fail 'Error bootstrapping'
  fi
fi

# source the new bash configuration
source ~/.bashrc

if [ -z ${DOTUPDATE+x} ];then
  tada "dot.minatrix installed successfully!"
else
  tada "dot.minatrix updated successfully!"
fi
echo ''
echo "$(<$AFTERINSTALL)"

rm $AFTERINSTALL
unset AFTERINSTALL
