#!/usr/bin/env bash
#
# Run package installation and all topic installers.

set -e

# Ensure sudo for package installation
if [[ $UID != 0 ]]; then
  echo "Package installation requires sudo:"
  echo "sudo $0 $*"
  exit 1
fi

cd "$(dirname $0)"/..

echo ''

source script/helpers.sh

# load default packages
source packages.sh

# begin install
echo "Installing core packages: [${packagelist[@]}]"
apt install ${packagelist[@]}

# find the installers and run them iteratively
shopt -s extglob
for file in ./!(script)/install; do
  [ -f "$file" ] && [ -x "$file" ] && $file
done
