#!/bin/bash
#
# Run package installation and all topic installers.

if [ -z ${DOTFILES+x} ];then
  export DOTFILES=~/dot.minatrix
fi

source $DOTFILES/script/helpers

ensure-sudo

cd "$(dirname $0)"/..

shopt -s extglob

export DOTUPDATE=1
if [ -z ${DOTUPDATE+x} ];then
  # load default packages
  source packages.bash

  # begin install
  for ppa in "${ppalist[@]}"; do
    inf "Adding custom PPA: ppa:$ppa"
    add-apt-repository "ppa:$ppa" -y
  done
  apt update

  inf "Installing core packages"
  apt install ${packagelist[@]}
fi

# find the installers and run them iteratively
export AFTERINSTALL='./AFTER_INSTALL_MESSAGE'

afterheader="
****************************
** After Install Messages **
****************************
"

for file in ./!(script)/install; do
  [ -f "$file" ] && [ -x "$file" ] && $file
done

if [ -z ${DOTUPDATE+x} ];then
  $DOTFILES/script/bootstrap
fi

echo "${afterheader}$(<$AFTERINSTALL)"

rm $AFTERINSTALL
unset AFTERINSTALL
